# Generated by Django 4.0.1 on 2022-01-15 23:02

from django.db import migrations, models
import services.account_recovery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverPasswordCode',
            fields=[
                ('id', models.CharField(default=services.account_recovery.utils.generate_password_recover_code, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'recover password code',
                'verbose_name_plural': 'recover password codes',
            },
        ),
    ]
